/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author MA
 */
public class SignUp_page extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public SignUp_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        username_Input = new javax.swing.JTextField();
        signup_Panel = new javax.swing.JPanel();
        firstName_Input = new javax.swing.JTextField();
        lastName_Input = new javax.swing.JTextField();
        welcomeSignupPage = new javax.swing.JLabel();
        email_Input = new javax.swing.JTextField();
        male_Input = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        female_Input = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        day_Input = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        year_Input = new javax.swing.JComboBox<>();
        Register_btn = new javax.swing.JButton();
        password_input_register = new javax.swing.JPasswordField();

        username_Input.setText("Username");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstName_Input.setText("First Name");
        firstName_Input.setToolTipText("First Name");
        firstName_Input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstName_InputMouseClicked(evt);
            }
        });
        firstName_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName_InputActionPerformed(evt);
            }
        });

        lastName_Input.setText("Last Name");
        lastName_Input.setToolTipText("Last Name");
        lastName_Input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastName_InputMouseClicked(evt);
            }
        });
        lastName_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName_InputActionPerformed(evt);
            }
        });

        welcomeSignupPage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeSignupPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeSignupPage.setText("Welcome to Signup page");

        email_Input.setText("Email");
        email_Input.setToolTipText("Email");
        email_Input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                email_InputMouseClicked(evt);
            }
        });
        email_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_InputActionPerformed(evt);
            }
        });

        buttonGroup1.add(male_Input);
        male_Input.setText("Male");
        male_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_InputActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Gender");

        buttonGroup1.add(female_Input);
        female_Input.setText("Female");
        female_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_InputActionPerformed(evt);
            }
        });

        jLabel2.setText("Already account");

        login_button.setBackground(new java.awt.Color(102, 102, 255));
        login_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_button.setText("Login");
        login_button.setToolTipText("Login page");
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_buttonMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Date Of Birth");

        day_Input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        year_Input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "19999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", " " }));

        Register_btn.setBackground(new java.awt.Color(102, 102, 255));
        Register_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Register_btn.setText("Register");

        password_input_register.setText("Password");
        password_input_register.setToolTipText("");
        password_input_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                password_input_registerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout signup_PanelLayout = new javax.swing.GroupLayout(signup_Panel);
        signup_Panel.setLayout(signup_PanelLayout);
        signup_PanelLayout.setHorizontalGroup(
            signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signup_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_button)
                .addGap(15, 15, 15))
            .addGroup(signup_PanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signup_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(male_Input)
                        .addGap(32, 32, 32)
                        .addComponent(female_Input)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(signup_PanelLayout.createSequentialGroup()
                        .addGroup(signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email_Input)
                            .addGroup(signup_PanelLayout.createSequentialGroup()
                                .addComponent(firstName_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(lastName_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(signup_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(day_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(year_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(password_input_register, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 29, Short.MAX_VALUE))))
            .addGroup(signup_PanelLayout.createSequentialGroup()
                .addGroup(signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signup_PanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(welcomeSignupPage, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signup_PanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Register_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signup_PanelLayout.setVerticalGroup(
            signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signup_PanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(welcomeSignupPage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(email_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male_Input)
                    .addComponent(jLabel1)
                    .addComponent(female_Input))
                .addGap(48, 48, 48)
                .addComponent(password_input_register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(day_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Register_btn)
                .addGap(9, 9, 9)
                .addGroup(signup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_button))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signup_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signup_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_InputActionPerformed
         email_Input.setText("");
    }//GEN-LAST:event_email_InputActionPerformed

    private void female_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_InputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_female_InputActionPerformed

    private void male_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_male_InputActionPerformed

    private void firstName_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName_InputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_firstName_InputActionPerformed

    private void lastName_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastName_InputActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lastName_InputActionPerformed

    private void lastName_InputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastName_InputMouseClicked
        // TODO add your handling code here:
         lastName_Input.setText("");
    }//GEN-LAST:event_lastName_InputMouseClicked

    private void firstName_InputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstName_InputMouseClicked
        // TODO add your handling code here:
        firstName_Input.setText("");
    }//GEN-LAST:event_firstName_InputMouseClicked

    private void email_InputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_InputMouseClicked
        // TODO add your handling code here:
        email_Input.setText("");
    }//GEN-LAST:event_email_InputMouseClicked

    private void login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseClicked
        // TODO add your handling code here:
        Login_page login_page = new Login_page();
        login_page.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_buttonMouseClicked

    private void password_input_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_input_registerMouseClicked
        // TODO add your handling code here:
        password_input_register.setText("");
    }//GEN-LAST:event_password_input_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> day_Input;
    private javax.swing.JTextField email_Input;
    private javax.swing.JRadioButton female_Input;
    private javax.swing.JTextField firstName_Input;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lastName_Input;
    private javax.swing.JButton login_button;
    private javax.swing.JRadioButton male_Input;
    private javax.swing.JPasswordField password_input_register;
    private javax.swing.JPanel signup_Panel;
    private javax.swing.JTextField username_Input;
    private javax.swing.JLabel welcomeSignupPage;
    private javax.swing.JComboBox<String> year_Input;
    // End of variables declaration//GEN-END:variables
}
